TFW_API_TOKEN         = "Ir00ktJ11ZwvdSoNX79E"
TFW_TICKETS_BASE_API  = "https://tickets.trc.cymru/api/v1/silverrail/"
TFW_STATIONS_BASE_API = "https://tfw.wales/api/"
TFW_FIND_STATIONS     = "silverrail-stations/find/"
TFW_TICKET_SEARCH     = f"ticketsearch?token={TFW_API_TOKEN}"